version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: cerbyd_postgres
    environment:
      POSTGRES_DB: cerbyd_triplogger
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: x836vzm7dI
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - cerbyd_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d cerbyd_triplogger"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./API
      dockerfile: Dockerfile
    container_name: cerbyd_api
    environment:
      DB_NAME: cerbyd_triplogger
      DB_USER: postgres
      DB_PASSWORD: x836vzm7dI
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cerbyd_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  ingestion:
    build:
      context: .
      dockerfile: Ingestion/Dockerfile
    container_name: cerbyd_ingestion
    environment:
      DB_NAME: cerbyd_triplogger
      DB_USER: postgres
      DB_PASSWORD: x836vzm7dI
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cerbyd_network
    restart: unless-stopped

  data_processor:
    build:
      context: .
      dockerfile: DB/Dockerfile
    container_name: cerbyd_processor
    environment:
      DB_NAME: cerbyd_triplogger
      DB_USER: postgres
      DB_PASSWORD: x836vzm7dI
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      db:
        condition: service_healthy
    networks:
      - cerbyd_network

volumes:
  postgres_data:
    driver: local

networks:
  cerbyd_network:
    driver: bridge